# Generated by Django 4.0.5 on 2022-07-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_stockgroup_remove_createstockgrp_under_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_item',
            name='under',
        ),
        migrations.AddField(
            model_name='stock_item',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockgroup'),
        ),
    ]
