# Generated by Django 4.0.5 on 2022-08-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_stock_item_under_stock_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item',
            name='opening_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vouch_type', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('value', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stock_item')),
            ],
        ),
    ]
