# Generated by Django 4.0.5 on 2022-08-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_stock_item_opening_balance_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='rateper',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
