# Generated by Django 4.0.5 on 2022-08-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_voucher_party_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='voucher',
            new_name='voucherlist',
        ),
    ]
