# Generated by Django 4.0.5 on 2022-08-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_stock_item_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherlist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockgroup'),
        ),
    ]
