# Generated by Django 4.0.5 on 2022-08-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_voucherlist_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='stock_item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockcategory'),
        ),
        migrations.AddField(
            model_name='voucherlist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockcategory'),
        ),
    ]
