# Generated by Django 4.0.5 on 2022-08-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_stockcategory_stock_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createstockcateg',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockcategory'),
        ),
        migrations.AddField(
            model_name='createstockgrp',
            name='under',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
