# Generated by Django 4.0.5 on 2022-08-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_createstockcateg_category_createstockgrp_under'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createstockcateg',
            old_name='under_name',
            new_name='under',
        ),
    ]
