# Generated by Django 4.0.5 on 2022-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_under_name_createstockcateg_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item',
            name='rateper',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
