# Generated by Django 4.0.5 on 2022-08-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_stock_item_quantity_alter_voucherlist_rateper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstockcateg',
            name='quantities',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createstockgrp',
            name='quantities',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock_item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_item',
            name='rateper',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voucherlist',
            name='rateper',
            field=models.IntegerField(null=True),
        ),
    ]
