# Generated by Django 4.0.5 on 2022-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_createstockcateg_quantities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstockgrp',
            name='quantities',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
