# Generated by Django 4.0.5 on 2022-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_createstockgrp_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstockcateg',
            name='quantities',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
