# Generated by Django 4.0.5 on 2022-08-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_createstockcateg_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
