# Generated by Django 4.0.5 on 2022-08-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountingGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builtgrp_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='createaccountingGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usergrp_name', models.CharField(max_length=100, null=True)),
                ('under', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.accountinggroups')),
            ],
        ),
    ]
