# Generated by Django 4.0.5 on 2022-08-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_accountinggroups_createaccountinggroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('under', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.createaccountinggroups')),
            ],
        ),
    ]
